# Generated by Django 5.0.6 on 2024-05-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
    ]
